version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/go:1.21.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: lint-dockerfile
          command: docker run --rm -i hadolint/hadolint < Dockerfile
      - run: 
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)
      - run:
          name: build-app-karsajobs
          command: ./build_push_image_karsajobs.sh

workflows:
  build:
    jobs:
      - build_and_push:
          context: github_packages